# Generated by Django 2.0.7 on 2018-07-17 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Functionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(blank=True, max_length=50, verbose_name='grupo')),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('membership', models.CharField(blank=True, max_length=100, verbose_name='filiação')),
                ('conjugate', models.CharField(blank=True, max_length=100, verbose_name='conjugue')),
                ('salary', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='salário')),
                ('note', models.TextField(blank=True, verbose_name='observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'funcionário',
                'verbose_name_plural': 'funcionários',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(blank=True, max_length=50, verbose_name='grupo')),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('note', models.TextField(blank=True, verbose_name='observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'fornecedor',
                'verbose_name_plural': 'fornecedores',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('number', models.AutoField(primary_key=True, serialize=False, verbose_name='número')),
                ('requester', models.CharField(blank=True, max_length=100, verbose_name='requisitante')),
                ('activity', models.CharField(blank=True, max_length=100, verbose_name='atividade')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='valor')),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='desconto')),
                ('state', models.CharField(choices=[('A', 'Aberto'), ('P', 'Pago')], default='A', max_length=1, verbose_name='situação')),
                ('note', models.TextField(blank=True, verbose_name='observações')),
                ('paid_at', models.DateTimeField(auto_now_add=True, verbose_name='pago em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('functionary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrations.Functionary', verbose_name='funcionário')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrations.Provider', verbose_name='fornecedor')),
            ],
            options={
                'verbose_name': 'requisição',
                'verbose_name_plural': 'requisições',
                'ordering': ('number',),
            },
        ),
    ]
