# Generated by Django 2.0.7 on 2018-07-18 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='functionary',
            options={'ordering': ('name',), 'verbose_name': 'índio', 'verbose_name_plural': 'índios'},
        ),
        migrations.AlterField(
            model_name='functionary',
            name='group',
            field=models.CharField(choices=[('functionary', 'Funcionário'), ('leadership', 'Liderança'), ('agricultural', 'Agríola'), ('retired', 'Aposentados'), ('agricultural wives', 'Esposas agricola'), ('cleaning', 'Limpeza'), ('education 1º step', 'Educação 1º etapa'), ('education 2º step', 'Educação 2º etapa'), ('krimeiruk wives', 'Esposas Krimeiruk'), ('kamkrokró wives', 'Esposas Kamkrokró'), ('purekokeí wives', 'Esposas Purokokeí')], default='functionary', max_length=50, verbose_name='grupo'),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='functionary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrations.Functionary', verbose_name='índio'),
        ),
    ]
