# Generated by Django 2.0.7 on 2018-08-04 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0002_auto_20180718_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='state',
            field=models.CharField(choices=[('C', 'Criada'), ('A', 'Aberto'), ('P', 'Pago')], default='C', max_length=1, verbose_name='situação'),
        ),
    ]
