# Generated by Django 2.0.7 on 2018-08-11 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0003_auto_20180804_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='functionary',
            name='group',
            field=models.CharField(choices=[('poultry farming', 'Avicultura'), ('beekeeping', 'Apicultura'), ('functionary', 'Funcionário'), ('leadership', 'Liderança'), ('agricultural', 'Agríola'), ('retired', 'Aposentados'), ('agricultural wives', 'Esposas agricola'), ('cleaning', 'Limpeza'), ('education 1º step', 'Educação 1º etapa'), ('education 2º step', 'Educação 2º etapa'), ('krimeiruk wives', 'Esposas Krimeiruk'), ('kamkrokró wives', 'Esposas Kamkrokró'), ('purekokeí wives', 'Esposas Purokokeí')], default='functionary', max_length=50, verbose_name='grupo'),
        ),
    ]
